app/main/forms.py
from flask.app import Flask
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField, DecimalField
from wtforms.fields.html5 import DateField
from wtforms.validators import ValidationError, DataRequired, InputRequired, Email
from app.helperfunc import check_and_clean_phone_number
from flask_login import current_user
from app.models import Company


class RegisterPackageForm(FlaskForm):
    phone = StringField(('Customer Phone Number'), validators=[DataRequired()])
    package_name = SelectField(('Package Name'), validators=[DataRequired()])
    package_num_total_uses_at_start = IntegerField(('No. times package can be used'), validators=[DataRequired()])
    package_num_used_when_keyed = IntegerField(('No. times package has already been used'), validators=[InputRequired()])
    package_price_paid = DecimalField(('Price Paid for Package (SGD)'), validators=[InputRequired()], places=2)
    submit = SubmitField(('Register package for customer'))

    def validate_phone(self, phone):
        try:
            check_and_clean_phone_number(phone.data)
        except:
            raise ValidationError(('Phone number is not valid'))


class PortCustomerAndPackageForm(FlaskForm):
    phone = StringField(('Customer Phone Number'), validators=[DataRequired()])
    name = StringField(('Customer Name'))
    package_name = SelectField(('Package Name'), validators=[DataRequired()])
    package_num_total_uses_at_start = IntegerField(('No. times package can be used'), validators=[DataRequired()])
    package_num_used_when_keyed = IntegerField(('No. times package has already been used'), validators=[InputRequired()])
    package_price_paid = DecimalField(('Price Paid for Package (SGD)'), places=2)
    created_at = DateField(format='%Y-%m-%d')
    submit = SubmitField(('Port new package'))

    def validate_phone(self, phone):
        try:
            check_and_clean_phone_number(phone.data)
        except:
            raise ValidationError(('Phone number is not valid'))


class TransferPackageForm(FlaskForm):
    phone = StringField(('Phone Number to transfer to'), validators=[DataRequired()])
    num_uses_to_transfer = IntegerField(('No. package uses to transfer'), validators=[DataRequired()])
    submit = SubmitField(('Transfer to friend'))

    def validate_phone(self, phone):
        try:
            check_and_clean_phone_number(phone.data)
        except:
            raise ValidationError(('Phone number is not valid'))


class AddCompanyItemForm(FlaskForm): # packages and services are the same thing
    item_name = StringField(validators=[DataRequired()])
    item_price = DecimalField(validators=[InputRequired()], places=2) 
    submit = SubmitField(('Register new item'))


class CreateProductOrderForm(FlaskForm):
    item_name = SelectField(('Package Name'), validators=[DataRequired()])
    item_price = DecimalField(('Item Price (SGD)'), validators=[InputRequired()], places=2) 
    item_discount = DecimalField(('Item Discount (SGD)'), places=2) 
    item_quantity = IntegerField(('Quantity'), validators=[DataRequired()]) 
    submit = SubmitField(('Add Product'))


class UpdateCustomerSettingsForm(FlaskForm):
    name = StringField(('Name'), validators=[DataRequired()])
    phone = StringField(('Phone Number'), validators=[DataRequired()])
    email = StringField(('Email'), validators=[DataRequired(), Email()])
    submit = SubmitField(('Submit'))


class UpdateAdminSettingsForm(FlaskForm):
    name = StringField(('Name'), validators=[DataRequired()])
    email = StringField(('Email'), validators=[DataRequired(), Email()])
    submit = SubmitField(('Submit'))


class SearchCustomerForm(FlaskForm):
    phone_or_email = StringField(('Phone Number or Email'), validators=[DataRequired()])
    submit = SubmitField(('Search for Customer'))


class UpdateAdminOutletForm(FlaskForm):
    outlet_chosen = SelectField(('Outlets'), validators=[DataRequired()])
    submit = SubmitField(('Change Outlet'))


class AddNewOutletForm(FlaskForm):
    outlet_name = StringField(('Outlet Name'), validators=[DataRequired()])
    postal = StringField(('Postal Code'), validators=[DataRequired()])
    unit_number = StringField(('Unit Number'), validators=[DataRequired()])
    address = StringField(('Address'), validators=[DataRequired()])
    phone = StringField(('Phone Number'), validators=[DataRequired()])
    email = StringField(('Email'), validators=[DataRequired(), Email()])
    submit = SubmitField(('Submit'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.auth.forms import ResetPasswordForm
from re import search
from app.main import bp
from app import db
from flask import render_template, flash, session, redirect, url_for, request
from app.decorators import login_required
from app.models import Company, Customer, Package, PackageUse, User, Admin, CompanyPackagesAndProducts, CustomerOrders, Outlet
from app.main.forms import CreateProductOrderForm, RegisterPackageForm, PortCustomerAndPackageForm, TransferPackageForm, SearchCustomerForm, AddCompanyItemForm, CreateProductOrderForm,\
UpdateCustomerSettingsForm, UpdateAdminSettingsForm, UpdateAdminOutletForm, AddNewOutletForm
from app.helperfunc import check_and_clean_phone_number, invalid_phone_number_message, check_if_cust_exists_else_create_return_custid
from flask_login import current_user
from app.main.email import send_package_invoice_email # to be enabled once in production
from sqlalchemy.sql.expression import func


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title='Home')


@bp.route('/admin', methods=['GET', 'POST'])
@bp.route('/admin/index', methods=['GET', 'POST'])
@login_required(role='admin')
def admin_home():
    admins_obj = Admin.query.filter_by(company_id=current_user.company_id).all()
    admin_data = [admin.list_admin_data() for admin in admins_obj]
    company_id = current_user.company_id
    form = SearchCustomerForm() # form will be in navigation.html, and not the base-admin page
    if form.validate_on_submit():
        # try to find customer using phone or email
        try: # case when customer keys in phone number
            phone_number = check_and_clean_phone_number(form.phone_or_email.data) # if email, exception is raised. if phone number is invalid 'None' returned
            customer = Customer.query.filter_by(phone=phone_number).first()
        except: # case when customer keys in email or if phone number is invalid
            customer = Customer.query.filter_by(email=form.phone_or_email.data).first()
        if customer is None :
            flash(('Customer email or phone not found. Please try again'), 'danger')
            del session['cust_id']
            return redirect(url_for('main.admin_home'))
        count_num_packages = Package.query.filter_by(company_id=company_id).filter_by(cust_id=customer.id).count()
        if count_num_packages == 0: # if customer exists, but does not have any packages with the salon
            flash(('Customer does not have any existing packages with your company.'), 'danger')
            del session['cust_id']
            return redirect(url_for('main.admin_home'))
        session['cust_id'] = customer.id 
        return redirect(url_for('main.customer_home_admin_view', cust_id=session['cust_id']))

    return render_template('admin_home.html', title='Admin Dashboard', admin_data=admin_data, form=form)


@bp.route('/admin/deactivate/<admin_id>', methods=['GET', 'POST'])
@login_required(role='admin')
def deactivate_admin(admin_id):
    a = Admin.query.filter_by(company_id=current_user.company_id).filter_by(id=admin_id).first()
    admin_name = a.name
    a.is_active = 0
    db.session.commit()
    flash(('Your have deactivated admin: {}.'.format(admin_name)), 'danger')
    return redirect(url_for('main.admin_home'))


@bp.route('/admin/activate/<admin_id>', methods=['GET', 'POST'])
@login_required(role='admin')
def activate_admin(admin_id):
    a = Admin.query.filter_by(company_id=current_user.company_id).filter_by(id=admin_id).first()
    admin_name = a.name
    a.is_active = 1
    db.session.commit()
    flash(('Your have activated admin: {}.'.format(admin_name)), 'success')
    return redirect(url_for('main.admin_home'))


@bp.route('/home', methods=['GET', 'POST'])
@login_required(role='customer')
def customer_home():
    # list package data
    packages = Package.query.filter_by(cust_id=current_user.id).all()
    package_data = [package.list_customer_package_data() for package in packages]
    return render_template('customer_home.html', title='Customer Home', package_data=package_data)

@bp.route('/admin/search-customer', methods=['GET', 'POST'])
@login_required(role='admin')
def search_for_customer(): # this does not filter customer by company. This filters every customer in the database with Stabl
    company_id = current_user.company_id
    form = SearchCustomerForm()
    if form.validate_on_submit():
        # try to find customer using phone or email
        try: # case when customer keys in phone number
            phone_number = check_and_clean_phone_number(form.phone_or_email.data) # if email, exception is raised. if phone number is invalid 'None' returned
            customer = Customer.query.filter_by(phone=phone_number).first()
        except: # case when customer keys in email or if phone number is invalid
            customer = Customer.query.filter_by(email=form.phone_or_email.data).first()
        if customer is None :
            flash(('Customer email or phone not found. Please try again'), 'danger')
            return redirect(url_for('main.search_for_customer'))
        count_num_packages = Package.query.filter_by(company_id=company_id).filter_by(cust_id=customer.id).count()
        if count_num_packages == 0: # if customer exists, but does not have any packages with the salon
            flash(('Customer does not have any existing packages with your company.'), 'danger')
            return redirect(url_for('main.search_for_customer'))
        session['cust_id'] = customer.id 
        return redirect(url_for('main.customer_home_admin_view', cust_id=session['cust_id']))
    return render_template('main/search_for_customer.html', title='Find customer', form=form)


@bp.route('/admin/customer-home/<cust_id>', methods=['GET', 'POST'])
@login_required(role='admin')
def customer_home_admin_view(cust_id):
    # list package data
    packages = Package.query.filter_by(company_id=current_user.company_id).filter_by(cust_id=session['cust_id']).all()
    package_data = [package.list_customer_package_data() for package in packages]
    return render_template('customer_home.html', title='Home', package_data=package_data)


@bp.route('/admin/new-package', methods=['GET', 'POST'])
@login_required(role='admin')
def register_new_package():
    form = RegisterPackageForm()
    company_id = current_user.company_id
    # populate package_choices
    company_packages_obj = CompanyPackagesAndProducts.query.filter_by(company_id=company_id).filter_by(item_type='service').all()
    form.package_name.choices = [(p.item_name) for p in company_packages_obj]
    if form.validate_on_submit():
        if current_user.outlet_id is None:
            flash(('The data you entered does not make sense. Please check and try again.'), 'danger')
            return redirect(url_for('main.port_customer_and_package'))
        phone_number = check_and_clean_phone_number(form.phone.data)
        cust_id = check_if_cust_exists_else_create_return_custid(phone=phone_number)
        package_num_total_uses_at_start = form.package_num_total_uses_at_start.data
        package_num_used_when_keyed = form.package_num_used_when_keyed.data
        package_price_paid_in_cents = int((form.package_price_paid.data) * 100)
        company_id = company_id

        if package_num_total_uses_at_start <= package_num_used_when_keyed or package_price_paid_in_cents < 0:
            flash(('The data you entered does not make sense. Please check and try again.'), 'danger')
            return redirect(url_for('main.register_new_package'))
        new_package = Package(
            admin_id=current_user.get_id(),
            outlet_id=current_user.outlet_id,
            outlet_name=current_user.outlet_name, 
            cust_id=cust_id,
            company_id=company_id,
            package_name=form.package_name.data,
            package_num_total_uses_at_start=package_num_total_uses_at_start,
            package_num_used_when_keyed=package_num_used_when_keyed,
            package_price_paid_in_cents=package_price_paid_in_cents
            )
        db.session.add(new_package)
        db.session.commit()
        flash(('You have created a package for customer with phone number: {}'.format(phone_number)), 'success')
        # send_package_invoice_email(current_user)
        return redirect(url_for('main.admin_home'))
    return render_template('main/register_new_package.html', title='Migrate New Package', form=form)


@bp.route('/package/use-package/<package_id>', methods=['GET', 'POST'])
@login_required()
def use_package(package_id):
    package_user_id = current_user.id
    package_user_role = current_user.role

    p = Package.query.filter_by(id=package_id).first_or_404()

    num_uses_left = p.num_uses_left()
    if num_uses_left <= 0:
        p.is_active = 0
        db.session.commit()
        flash('You have finished using this package.', 'danger')
        return redirect(url_for('main.display_package_summary', package_id=package_id))
    else:
        if num_uses_left == 1:
            p.is_active = 0
        p.package_num_times_used_after_keyed = p.package_num_times_used_after_keyed + 1
        # insert package use data
        package_use = PackageUse(package_id=package_id)
        package_use.num_uses = 1 # number times package used is 1 time
        package_use.who_used_package_id = package_user_id
        if package_user_role != 'customer': # if admin use package, take down the name of the admin
            admin_name = Admin.query.filter_by(id=package_user_id).first().name
            package_use.who_used_package = 'Staff ({})'.format(admin_name)
        else: # else, it's the self who use package
            package_use.who_used_package = 'self'
        db.session.add(package_use)
        db.session.commit()
        flash('Congrats! You have used this package', 'success')
        return redirect(url_for('main.display_package_summary', package_id=package_id))

app/templates/main/add_new_outlet.html
{% extends "layouts/base-admin.html" %}

{% block title %} {{ title }} {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="col-12 col-sm-12 col-xl-12 mb-4">
        <div class="card border-light shadow-sm">
            <div class="card-body">
                <!-- Package Use -->
                <div class="card-header">
                    <h2 class="fs-5 fw-bold mb-0">{{ title }}</h2><br>
                    <!-- Button Modal -->
                    <a class="btn btn-sm btn-info" href="#modalNewOutlet" data-bs-toggle="modal"><span class="fas fa-store mr-1"></span> Add new outlet </a>

                </div>
                {% for outlet in outlets_data %}
                <div class="card-body">
                    <!-- Packaged transferred -->
                    <div class="row ps-lg-1">
                        <div class="col ms-n2">
                            <h3 class="fs-5 fw-bold mb-1">{{ outlet.outlet_name }}</h3>
                            <p class="mb-1"><b>Address:</b> #{{ outlet.unit_number  }} {{ outlet.address}}, S({{ outlet.postal }})</p>
                            <p class="mb-1"><b>Phone:</b> {{ outlet.phone }}</p>
                            <p class="mb-1"><b>Email:</b> {{ outlet.email }}</p>
                        </div>
                    </div>
                    <a class="btn btn-sm btn-secondary" href="{{ url_for('main.edit_outlet_data', outlet_id=outlet.outlet_id) }}"><span class="fas fa-edit mr-1"></span> Edit </a>
                    <!-- Button Modal -->
                    <a class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#modal-delete{{ outlet.outlet_id }}"><span class="fas fa-minus mr-1"></span> Delete </a>
                    <!-- Modal Content -->
                    <div class="modal fade" id="modal-delete{{ outlet.outlet_id }}" tabindex="-1" role="dialog" aria-labelledby="modal-notification" aria-hidden="true">
                        <div class="modal-dialog modal-info modal-dialog-centered" role="document">
                            <div class="modal-content bg-gradient-secondary">
                                <div class="modal-header">
                                    <p class="modal-title" id="modal-title-notification">Please confirm deletion.</p>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="py-3 text-center">
                                        <span class="modal-icon display-1-lg"><span class="far fa-envelope-open"></span></span>
                                        <h2 class="h4 modal-title my-3">Important message!</h2>
                                        <p>Are you sure you want to delete this outlet? This action cannot be undone.</p>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-sm btn-danger" href="{{ url_for('main.delete_existing_outlet', outlet_id=outlet.outlet_id) }}"> Delete Outlet </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End of Modal Content -->
                </div>
                
                {% endfor %}

                <!-- Modal Content -->
                <div class="modal fade" id="modalNewOutlet" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header border-0">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body px-md-5">
                                <h2 class="h4 text-center">Add New Outlet</h2>
                                <p class="text-center mb-4">Enter outlet details for customers to find you</p>
                                <form method="post" action="" class="mt-4">
                                    {{ form.hidden_tag() }}
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Outlet Name</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><span class="fas fa-store"></span></span>
                                            {{ form.outlet_name(placeholder="E.g. Roxy Square", class="form-control") }}
                                        </div>
                                        <p class="text-danger">{% for errors in form.outlet_name.errors %}{{ errors }}{% endfor %}</p>
                                    </div>
                                    <!-- End of Form -->
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Postal</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><span class="fas fa-mail-bulk"></span></span>
                                            {{ form.postal(placeholder="E.g. 123456", class="form-control") }}
                                        </div>
                                        <p class="text-danger">{% for errors in form.postal.errors %}{{ errors }}{% endfor %}</p>
                                    </div>
                                    <!-- End of Form -->
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Unit Number</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><span class="fas fa-sign"></span></span>
                                            {{ form.unit_number(placeholder="E.g. 01-23", class="form-control") }}
                                        </div>
                                        <p class="text-danger">{% for errors in form.unit_number.errors %}{{ errors }}{% endfor %}</p>
                                    </div>
                                    <!-- End of Form -->
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Address</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><span class="fas fa-map-marker-alt"></span></span>
                                            {{ form.address(placeholder="E.g. 50 East Coast Road", class="form-control") }}
                                        </div>
                                        <p class="text-danger">{% for errors in form.address.errors %}{{ errors }}{% endfor %}</p>
                                    </div>
                                    <!-- End of Form -->
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Outlet Phone Number</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><span class="fas fa-phone"></span></span>
                                            {{ form.phone(placeholder="E.g. 91000000", class="form-control") }}
                                        </div>  
                                        <p class="text-danger">{% for errors in form.phone.errors %}{{ errors }}{% endfor %}</p>
                                    </div>
                                    <!-- End of Form -->
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Outlet Email</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><span class="fas fa-envelope"></span></span>
                                            {{ form.email(placeholder="E.g. salon1@example.com", class="form-control") }}
                                        </div>
                                        <p class="text-danger">{% for errors in form.email.errors %}{{ errors }}{% endfor %}</p>
                                    </div>
                                    <!-- End of Form -->
     
                                    <div class="d-grid">
                                        <button type="submit" name="submit" class="btn btn-dark">Create New Outlet</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End of Modal Content -->

                </div>
                </div>
                </div>



                
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

app/templates/main/change_admin_outlet.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Change Outlet {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
            <div class="container px-0">
                <p class="text-center"><a href="{{ url_for('main.admin_home') }}" class="text-gray-700"><i class="fas fa-angle-left me-2"></i>Back to homepage</a></p>
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="mb-4 mb-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <p>New orders on this account will be tagged to your current outlet. This makes it easier to track the sales of each store.</p>
                                <h1 class="mb-0 h3">Your current outlet: <b>{{current_user.outlet_name }}</b></h1>
                            </div>

                            <form method="post" action="" class="mt-4">
                                {{ form.hidden_tag() }}
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Change Your Default Outlet</label>
                                    <div class="input-group">
                                        {{ form.outlet_chosen(class="form-select") }}
                                    </div>
                                    <p class="text-danger">{% for errors in form.outlet_chosen.errors %}{{ errors }}{% endfor %}</p>
                                    <p class="small"> <u><a class="text-info" href="{{ url_for('main.add_new_outlet') }}">Add a new outlet here</a></u> if you can't find what you want</p>
                                </div>
                                <!-- End of Form --> 
                                <div class="d-grid">
                                    <button type="submit" name="submit" class="btn btn-dark">Change Default Outlet</button>
                                </div>
                            </form>

                        </div>
                    </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/main/transfer_package.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Transfer Package {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
            <div class="container px-0">
                {% if current_user.role=='customer' %}
                <p class="text-center"><a href="{{ url_for('main.customer_home') }}" class="text-gray-700"><i class="fas fa-angle-left me-2"></i>Back to homepage</a></p>
                {% elif current_user.role=='admin' %}
                <p class="text-center"><a href="{{ url_for('main.admin_home') }}" class="text-gray-700"><i class="fas fa-angle-left me-2"></i>Back to homepage</a></p>
                {% endif %}
                <div class="row justify-content-center form-bg-image">
                    <div class="col-12 d-flex align-items-center justify-content-center px-0 px-sm-3">
                        <div class="mb-4 mb-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Transfer Package To A Friend</h1>
                                
                            </div>
                            <p><b>Package:</b> {{ package_data.package_name }}</p>
                            <p><b>Number of uses left:</b> {{ package_data.num_uses_left }}</p>
                        

                            <form method="post" action="" class="mt-4">
                                {{ form.hidden_tag() }}
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Phone Number to transfer to</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><span class="fas fa-phone"></span></span>
                                        {{ form.phone(placeholder="Phone", class="form-control") }}
                                    </div>  
                                    <p class="text-danger">{% for errors in form.phone.errors %}{{ errors }}{% endfor %}</p>
                                </div>
                                <!-- End of Form -->
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">No. package uses to transfer</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><span class="fas fa-list-ol"></span></span>
                                        {{ form.num_uses_to_transfer(class="form-control") }}
                                    </div>
                                    <p class="text-danger">{% for errors in form.num_uses_to_transfer.errors %}{{ errors }}{% endfor %}</p>
                                </div>
                                <!-- End of Form -->
 
                                <div class="d-grid">
                                    <button type="submit" name="submit" class="btn btn-dark">Transfer to friend</button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}